apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: real-fake-sensors
  name: real-fake-sensors
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: real-fake-sensors
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/iot-system-prototype-default: "true"
        io.kompose.service: real-fake-sensors
    spec:
      containers:
        - image: real-fake-sensors
          name: real-fake-sensors
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
