apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: sensational-sensors
  name: sensational-sensors
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensational-sensors
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/iot-system-prototype-default: "true"
        io.kompose.service: sensational-sensors
    spec:
      containers:
        - image: sensational-sensors
          name: sensational-sensors
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
