version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=prod
  app:
    container_name: app
    build:
      context: .
      dockerfile: app_vue/Dockerfile
    ports:
      - "3000:5173"
    environment:
      - NEXT_PUBLIC_API_HOST=http://api:8080
    depends_on:
      - api
