version: "3.9"

services:
  real-fake-sensors:
    container_name: real-fake-sensors
    build:
      context: .
      dockerfile: real-fake-sensors/Dockerfile
    ports:
      - "8081:8081"
  sensational-sensors:
    container_name: sensational-sensors
    build:
      context: .
      dockerfile: sensational-sensors/Dockerfile
    ports:
      - "8082:8082"
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - real-fake-sensors
      - sensational-sensors
    environment:
      - ENVIRONMENT=prod
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST=http://api:8080
    depends_on:
      - api
