version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=prod
  app:
    container_name: app
    build:
      context: .
      dockerfile: app_vue/Dockerfile
    ports:
      - "80:5173"
    environment:
      - VUE_APP_API_HOST=http://34.123.69.225:8080
    depends_on:
      - api
