-- Deploy wavdb:add_tekelek_records to pg
-- requires: create_tekelek_tbl

BEGIN;

INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Smart warehousing 6yd Front Load', NULL, 'Smart Warehousing', '6560 Northwest Dr', 'Mississauga', 'ON', 'L4V 1P2', 43.70231876, -79.62619739, 'East', 'Garbage', '6 cyd', 'Front load', NULL, '1B3364', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Logistics', 84, 99, 80, 85, TRUE, TRUE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Malton Best 15yd Roll Off', NULL, 'Malton Best Inc. - Sheet Metal Fabrication ', '6750 Professional Ct.', 'Mississauga', 'ON', 'L4V 1X6', 43.70553271, -79.62843006, 'East', 'Scrap Metal', '15 cyd', 'Roll off', NULL, '1B3365', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95, 97, 75, 85, FALSE, FALSE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Punjab Business Centre 6yd Front Load - 1', NULL, 'The Great Punjab Business Centre', '2980 Drew Rd.', 'Mississauga', 'ON', 'L4T 0A7', 43.70852633, -79.65335383, 'West', 'Garbage', '6 cyd', 'Front load', NULL, '2077C4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 54, 90, 75, 70, TRUE, TRUE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Punjab Business Centre 6yd Front Load - 2', NULL, 'The Great Punjab Business Centre', '2980 Drew Rd.', 'Mississauga', 'ON', 'L4T 0A7', 43.70852633, -79.65335383, 'West', 'Cardboard', '6 cyd', 'Front load', NULL, '2078C1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 89, 89, 75, 70, TRUE, TRUE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('ETG Commodities 360L Tote - 1', NULL, 'ETG Commodities Inc. - Food Processing', '6601 Goreway Dr Unit B', 'Mississauga', 'ON', 'L4V 1V6', 43.71029174, -79.61618655, 'East', 'Compost', '360 L', 'Tote', NULL, '29ED704', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 78, 82, 75, 85, FALSE, FALSE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Popeyes Airport 6yd Front Load', NULL, 'Popeyes Louisiana Kitchen', '6795 Airport Rd.', 'Mississauga', 'ON', 'L4V 1E6', 43.70026964, -79.63606049, 'South', 'Garbage', '6 cyd', 'Front load', NULL, '860147041814987', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Restaurant', 67, 82, 95, 85, TRUE, TRUE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Tim Hortons Airport 6yd Front Load', NULL, 'Tim Hortons', '6767 Airport Rd.', 'Mississauga', 'ON', 'L4V 1E6', 43.69968208, -79.63585205, 'South', 'Garbage', '6 cyd', 'Front load', NULL, '860536048877304', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Restaurant', 53, 78, 75, 85, FALSE, FALSE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Firehouse Subs Airport 6yd Front Load', NULL, 'Firehouse Subs Airport Rd-Mississauga', '6815 Airport Rd.', 'Mississauga', 'ON', 'L4V 1E6', 43.70057959, -79.63701448, 'South', 'Garbage', '6 cyd', 'Front load', NULL, '862061040704024', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Restaurant', 97, 75, 75, 85, TRUE, TRUE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('Toronto Aircraft Maintenance 8yd Front Load', NULL, 'Toronto Aircraft Maintenance', '2450 Derry Rd E. Hangar 8B', 'Mississauga', 'ON', 'L5S 1B2', 43.6928365, -79.64964406, 'South', 'Garbage', '8 cyd', 'Front load', NULL, '862315069676244', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 72, 75, 75, 85, FALSE, FALSE, NULL);
INSERT INTO wav_schema.tekelek (asset_name, device_bin_location_description, customer_name, bin_address, city, province, postal_code, latitude, longitude, group_name, material_waste_type, bin_volume, bin_type, bin_manufacturer_description, sensor_id, sensor_manufacturer_description, hauler, task_required, bin_height_in, bin_diameter_width_in, sensor_height_in, from_sensor_to_opening_of_the_bin_in, image_of_bin, additional_asset_tags, fill_level_last_collected, fill_level, fill_level_alert, temperature_alert, illegal_dumping_alert, contamination_alert, last_collected) VALUES ('TJX 3yd Front Load - 1', NULL, 'TJX Canada - American Drive Distribution Centre (ADC)', '3185 American Dr.', 'Mississauga', 'ON', 'L4V 1B8', 43.69338627, -79.61855354, 'East', 'Garbage', '3 cyd', 'Front load', NULL, '868326028641728', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Logistics', 93, 68, 75, 85, FALSE, FALSE, NULL);

UPDATE wav_schema.tekelek
SET last_collected = CURRENT_DATE - (1 + RANDOM() * 2)::INTEGER + (RANDOM() * 19)::INTEGER * interval '1 hour' + (RANDOM() * 59)::INTEGER * interval '1 minute' + (RANDOM() * 59)::INTEGER * interval '1 second'
WHERE last_collected IS NULL;


COMMIT;
