apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-ingress
spec:
  rules:
    - host: iot.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sensational-sensor-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /sensors
            backend:
              service:
                name: sensational-sensor-service
                port:
                  number: 8080
