apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: real-fake-sensors
  name: real-fake-sensors
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: real-fake-sensors
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/iot-system-prototype-default: "true"
        io.kompose.service: real-fake-sensors
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - image: ghcr.io/button-inc/iot-system-prototype/real_fake_sensors:38bd28cbfd10f1b4d3d80ce30519cb667ff8f1c3
          name: real-fake-sensors
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
