apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    service: api
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    name: http
  selector:
    app: real_fake_sensors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1
  labels:
    app: api
    version: v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: v1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
      - name: api
        image: ghcr.io/button-inc/iot-system-prototype/api:latest
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "32Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
