apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    service: app
  namespace: default
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app
    version: v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: app
        image: ghcr.io/button-inc/iot-system-prototype/app:latest
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "32Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
